### ISSUE TITLE
Command line arguments can be read

### ISSUE THREAD

**Issue by ankushdharkar** [Whymess/collaboration#1]
Pass as `node index.js data/comma.csv comma data/pipe.csv pipe data/dollar.csv dollar`

**Comment by ankushdharkar** [comment]
I ran the program, and got this *incorrect* result:

![image](https://user-images.githubusercontent.com/1935403/33565607-9af89a9e-d943-11e7-8a32-b474af330636.png)

**Comment by Whymess** [comment]
node index.js data/comma.csv , data/pipe.csv '|' data/dollar.csv $  that should work
